# Generated by Django 4.1.5 on 2023-01-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsaggregator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descrption',
            new_name='description',
        ),
    ]
