# Generated by Django 4.1.5 on 2023-02-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsaggregator', '0003_remove_post_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
